from opensearchpy import OpenSearch

host = 'localhost'
port = 9200
auth = ('admin', 'admin')  # Default credentials, change as necessary

client = OpenSearch(
    hosts=[{'host': host, 'port': port}],
    http_auth=auth,
    use_ssl=False,
    verify_certs=False,
    ssl_assert_hostname=False,
    ssl_show_warn=False,
)

index_name = "autocomplete"
documents = [
    {"id": 1, "name": "Apple"},
    {"id": 2, "name": "Banana"},
    {"id": 3, "name": "Cherry"},
    {"id": 4, "name": "Date"},
    {"id": 5, "name": "Eggplant"},
    {"id": 6, "name": "Fig"},
    {"id": 7, "name": "Grape"},
    {"id": 8, "name": "Honeydew"},
    {"id": 9, "name": "Iceberg Lettuce"},
    {"id": 10, "name": "Jalapeno"},
    {"id": 11, "name": "Kiwi"},
    {"id": 12, "name": "Lemon"},
    {"id": 13, "name": "Mango"},
    {"id": 14, "name": "Nectarine"},
    {"id": 15, "name": "Orange"},
    {"id": 16, "name": "Papaya"},
    {"id": 17, "name": "Quince"},
    {"id": 18, "name": "Raspberry"},
    {"id": 19, "name": "Strawberry"},
    {"id": 20, "name": "Tomato"},
    {"id": 21, "name": "Ugli Fruit"},
    {"id": 22, "name": "Vanilla Bean"},
    {"id": 23, "name": "Watermelon"},
    {"id": 24, "name": "Xigua"},
    {"id": 25, "name": "Yam"},
    {"id": 26, "name": "Zucchini"},
    {"id": 27, "name": "Al Dente"},
    {"id": 28, "name": "Blanch"},
    {"id": 29, "name": "Chiffonade"},
    {"id": 30, "name": "Deglaze"},
    {"id": 31, "name": "Emulsify"},
    {"id": 32, "name": "Flambé"},
    {"id": 33, "name": "Garnish"},
    {"id": 34, "name": "Hollandaise"},
    {"id": 35, "name": "Infuse"},
    {"id": 36, "name": "Julienne"},
    {"id": 37, "name": "Knead"},
    {"id": 38, "name": "Liaison"},
    {"id": 39, "name": "Macerate"},
    {"id": 40, "name": "Nage"},
    {"id": 41, "name": "Omelette"},
    {"id": 42, "name": "Poach"},
    {"id": 43, "name": "Quenelle"},
    {"id": 44, "name": "Reduction"},
    {"id": 45, "name": "Sauté"},
    {"id": 46, "name": "Temper"},
    {"id": 47, "name": "Umami"},
    {"id": 48, "name": "Velouté"},
    {"id": 49, "name": "Whip"},
    {"id": 50, "name": "Xanthan Gum"},
    {"id": 51, "name": "Yield"},
    {"id": 52, "name": "Zest"},
    {"id": 53, "name": "Bain-marie"},
    {"id": 54, "name": "Confit"},
    {"id": 55, "name": "Dredge"},
    {"id": 56, "name": "Escabeche"},
    {"id": 57, "name": "Fond"},
    {"id": 58, "name": "Gratin"},
    {"id": 59, "name": "Hasselback"},
    {"id": 60, "name": "Inoculate"},
    {"id": 61, "name": "Jus"},
    {"id": 62, "name": "Kishk"},
    {"id": 63, "name": "Lyonnaise"},
    {"id": 64, "name": "Mirepoix"},
    {"id": 65, "name": "Nappe"},
    {"id": 66, "name": "Oblique Cut"},
    {"id": 67, "name": "Paillard"},
    {"id": 68, "name": "Quinoa"},
    {"id": 69, "name": "Roux"},
    {"id": 70, "name": "Sous Vide"},
    {"id": 71, "name": "Tapenade"},
    {"id": 72, "name": "Umeboshi"},
    {"id": 73, "name": "Vichyssoise"},
    {"id": 74, "name": "Wasabi"},
    {"id": 75, "name": "Xocolatl"},
    {"id": 76, "name": "Yakitori"},
    {"id": 77, "name": "Zabaglione"},
    {"id": 78, "name": "Aioli"},
    {"id": 79, "name": "Bouquet Garni"},
    {"id": 80, "name": "Charcuterie"},
    {"id": 81, "name": "Dashi"},
    {"id": 82, "name": "Espagnole"},
    {"id": 83, "name": "Fumet"},
    {"id": 84, "name": "Galette"},
    {"id": 85, "name": "Haricot Vert"},
    {"id": 86, "name": "Involtini"},
    {"id": 87, "name": "Jicama"},
    {"id": 88, "name": "Kombu"},
    {"id": 89, "name": "Lardons"},
    {"id": 90, "name": "Microgreens"},
    {"id": 91, "name": "Nori"},
    {"id": 92, "name": "Osso Buco"},
    {"id": 93, "name": "Panzanella"},
    {"id": 94, "name": "Queso Fresco"},
    {"id": 95, "name": "Remoulade"},
    {"id": 96, "name": "Sofrito"},
    {"id": 97, "name": "Torchon"},
    {"id": 98, "name": "Udon"},
    {"id": 99, "name": "Veal Stock"},
    {"id": 100, "name": "Wakame"},
    {"id": 101, "name": "Xo Sauce"},
    {"id": 102, "name": "Yuzu"},
    {"id": 103, "name": "Zuppa"},
    {"id": 104, "name": "Amuse-bouche"},
    {"id": 105, "name": "Brunoise"},
    {"id": 106, "name": "Consommé"},
    {"id": 107, "name": "Duxelles"},
    {"id": 108, "name": "Emince"},
    {"id": 109, "name": "Fricassee"},
    {"id": 110, "name": "Gremolata"},
    {"id": 111, "name": "Harissa"},
    {"id": 112, "name": "Imbue"},
    {"id": 113, "name": "Jambalaya"},
    {"id": 114, "name": "Kugel"},
    {"id": 115, "name": "Lox"},
    {"id": 116, "name": "Mignonette"},
    {"id": 117, "name": "Nuoc Cham"},
    {"id": 118, "name": "Orzo"},
    {"id": 119, "name": "Pesto"},
    {"id": 120, "name": "Quark"}
]


for doc in documents:
    response = client.index(index=index_name, body=doc, id=doc['id'])
    print(response)
